version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "sylvester-francis"
    assignees:
      - "sylvester-francis"
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "sylvester-francis"
    assignees:
      - "sylvester-francis"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    reviewers:
      - "sylvester-francis"
    assignees:
      - "sylvester-francis"
    commit-message:
      prefix: "ci"
      include: "scope"