[tool.ruff]
line-length = 100
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I", "N", "W", "B", "C4", "SIM", "ARG"]
ignore = ["E203"]

[tool.ruff.lint.isort]
known-first-party = ["backend", "cli", "dashboard"]


[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"
python_functions = "test_*"
python_classes = "Test*"
addopts = "--cov=backend --cov=cli --cov=dashboard --cov-report=term-missing"
