---
apiVersion: v1
kind: Pod
metadata:
  name: app-1
  labels:
    app_id: "app-1"
    sw_version: "1.0.0"
    status: "idle"
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]

---
apiVersion: v1
kind: Pod
metadata:
  name: app-2
  labels:
    app_id: "app-2"
    sw_version: "1.0.0"
    status: "idle"
spec:
  containers:
    - name: busybox
      image: busybox
      command: ["sleep", "3600"]