name: Bazel Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Bazel
      uses: bazelbuild/setup-bazelisk@v2
      with:
        bazelisk-version: 'v1.26.0'
    
    # Disable cache to avoid the 422 error
    # - name: Mount bazel cache
    #   uses: actions/cache@v3
    #   with:
    #     path: "~/.cache/bazel"
    #     key: bazel-${{ runner.os }}-${{ github.sha }}
    #     restore-keys: bazel-${{ runner.os }}-
    
    - name: Build
      run: |
        bazel --output_base=/tmp/bazel-output build //...
      
    - name: Test
      run: |
        bazel --output_base=/tmp/bazel-output test //...
      
    - name: Build Docker Images
      run: |
        bazel --output_base=/tmp/bazel-output build :api_server_image
        bazel --output_base=/tmp/bazel-output build :dashboard_image
        bazel --output_base=/tmp/bazel-output build :job_runner_image
      
    # Disable coverage for now as it might be causing issues
    # - name: Coverage
    #   run: |
    #     bazel coverage //...
