name: Bazel Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Bazelisk manually
      run: |
        mkdir -p $HOME/bin
        wget -O $HOME/bin/bazel https://github.com/bazelbuild/bazelisk/releases/download/v1.16.0/bazelisk-linux-amd64
        chmod +x $HOME/bin/bazel
        echo "$HOME/bin" >> $GITHUB_PATH
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build
      run: |
        bazel --bazelrc=/dev/null build //...
      
    - name: Test
      run: |
        bazel --bazelrc=/dev/null test //...
