name: Deploy

on:
  workflow_run:
    workflows: ["Docker Build and Publish"]
    branches: [main]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
          
      - name: Deploy to Kubernetes
        run: |
          # Set the image tags to the latest build
          export API_IMAGE=ghcr.io/${{ github.repository }}-api:sha-$(git rev-parse --short HEAD)
          export DASHBOARD_IMAGE=ghcr.io/${{ github.repository }}-dashboard:sha-$(git rev-parse --short HEAD)
          export JOB_RUNNER_IMAGE=ghcr.io/${{ github.repository }}-job-runner:sha-$(git rev-parse --short HEAD)
          
          # Apply Kubernetes manifests with environment variables
          envsubst < k8s/deployment.yaml | kubectl apply -f -
          
      - name: Verify deployment
        run: |
          kubectl rollout status deployment/ota-api
          kubectl rollout status deployment/ota-dashboard
          kubectl rollout status deployment/ota-job-runner
